services:
  database:
    image: 'postgres:15.2'
    env_file: .env
    ports:
      - ${DB_PORT_ON_HOST}:${DB_PORT_ON_CONTAINER}

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@host.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    links:
      - database
    depends_on:
      - database

  api:
    build:
      context: .
    container_name: help-api
    env_file: .env
    volumes:
      - ./:/app
    command: ./gradlew bootRun
    ports:
      - ${API_PORT_ON_HOST}:${API_PORT_ON_CONTAINER}
    links:
      - database
    depends_on:
      - database