spring:
  datasource:
    url: jdbc:postgresql://172.18.0.2:5432/helpapp
    username: helpapp
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  docker:
    compose:
      enabled: false
  devtools:
    remote:
      secret: mysecret