CREATE TABLE answer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   message VARCHAR(255) NOT NULL,
   author_id BIGINT,
   post_id BIGINT,
   answer_id BIGINT,
   is_solution BOOLEAN NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   CONSTRAINT pk_answer PRIMARY KEY (id)
);

CREATE TABLE answer_like (
  answer_id BIGINT NOT NULL,
   user_id BIGINT NOT NULL
);

ALTER TABLE answer ADD CONSTRAINT FK_ANSWER_ON_ANSWER FOREIGN KEY (answer_id) REFERENCES answer (id);

ALTER TABLE answer ADD CONSTRAINT FK_ANSWER_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE answer ADD CONSTRAINT FK_ANSWER_ON_POST FOREIGN KEY (post_id) REFERENCES post (id);

ALTER TABLE answer_like ADD CONSTRAINT fk_anslik_on_answer FOREIGN KEY (user_id) REFERENCES answer (id);

ALTER TABLE answer_like ADD CONSTRAINT fk_anslik_on_user FOREIGN KEY (answer_id) REFERENCES users (id);