name: Automerge

on:
  push:
    branches:
      - developer
    
env:
  MY_REPO: https://RaphaelDaSilvaDev:${{secrets.GITHUB_TOKEN}}@github.com/RaphaelDaSilvaDev/Help-App-Api.git
  MY_BRANCH: developer
  MASTER_REPO: https://github.com/RaphaelDaSilvaDev/Help-App-Api
  MASTER_BRANCH: master
  
jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} tmp
        cd tmp
        git config user.name "RaphaelDaSilvaDev"
        git config user.email "raphael.h.silva@protonmail.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MY_BRANCH}}
        git push
